### ISSUE TITLE
GET(path.command_tree_node_for_command) needs to notify if context filtering needs to change

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#10]
If requesting to go to command x in a filtered tree, where x is in a different context (i.e. not part of the given tree), the server needs to tell the client to switch trees. The API already kind of allows this, by having the returned path point to a different tree ID, however, I saw in the code that it just passes back the same ID as was passed in. Also, I would need some way of telling what the filters are for a given tree ID. A better option would be to return a {path.CommandTree, path.CommandTreeNode} tuple. I can also live with the restriction that if the atom is not part of the current tree, we always switch to an unfiltered tree (which I can detect by the tree ids not matching).

This is needed for the resources' goto action and the global goto atom action.

**Comment by ben-clayton** [comment]
> If requesting to go to command x in a filtered tree, where x is in a different context (i.e. not part of the given tree), the server needs to tell the client to switch trees. The API already kind of allows this, by having the returned path point to a different tree ID

That's the mechanism.

> however, I saw in the code that it just passes back the same ID as was passed in.

Which is correct. The Tree identifier is unique to the set of filters.

> Also, I would need some way of telling what the filters are for a given tree ID.

The client obtains the tree ID by asking for it with the set of filters. This is done by resolving `path.CommandTree`.

Unless I'm missing something, I don't think anything is missing from the API here.

**Comment by ben-clayton** [comment]
To be clear:

Client asks for a tree with the filtering / customization it wants with:

`Get(path.CommandTree{...})`

It gets back a `service.CommandTree` with a `path.CommandTreeNode` to the root node. Part of the `path.CommandTreeNode` is the tree identifier. This identifier is the unique identifier for the tree you asked for with `path.CommandTree`.

You can poke around the tree by creating derived `path.CommandTreeNodes` where you play with the `index` field.

If you want to locate a `path.CommandTreeNode` from a `path.Command`, use `Get(path.CommandTreeNodeForCommand)` carrying across the tree ID from the original `Get(path.CommandTree{...})` call.

**Comment by pmuetschard** [comment]
We're on the same page regarding everything in your "to be clear" message. Here's the situation I'm talking about:

Let's say a trace has two contexts, with "context 1" containing atoms [0,100] and [200,300], while atoms [101,199] are part of "context 2".

The user has selected "context 1" in the drop down, filtering the atom tree with ID xxx. The user then looks at textures, and clicks on a "goto reference" with atom 150 - or - the user uses the "goto atom" action with atom 150.

The client asks for the path.CTN using path.CTNForCommand with atom index 150 on tree xxx. Tree xxx doesn't contain atom 150. So, the server needs to return a path.CTN to tree yyy, which is either filtered by "context 2" or has no filter.

I get the path.CTN and notice the tree ID has changed, so I update the tree. But, I also need to update the context selector. How do I know what the filters are on tree yyy?

**Comment by ben-clayton** [comment]
> So, the server needs to return a path.CTN to tree yyy

Not sure about this. There's not just one yyy that the server could return - does the client want to preserve the other constraints? Does the command show up if those constraints are applied? This could be an exhaustive search and returning some arbitrary tree seems wrong.

My gut feeling is that this should be handled by the client. Either by graying out that jump reference (easiest), or adjusting the tree query to something that should always contain the node.

Happy to discuss options further.

**Comment by ben-clayton** [comment]
Server really should handle no-node cases better.
