### ISSUE TITLE
CommandTreeNode thumbnails ignore format

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#11]
It appears that the thumbnails for CTNs ignore the requested format. E.g. I'm requesting the following;
GET thumbnail { desired_max_width: 192 desired_max_height: 192 desired_format { uncompressed { format { components { data_type { integer { bits: 8 } } sampling { normalized: true } channel: Red } components { data_type { integer { bits: 8 } } sampling { normalized: true } channel: Green } components { data_type { integer { bits: 8 } } sampling { normalized: true } channel: Blue } components { data_type { integer { bits: 8 } } sampling { normalized: true } channel: Alpha } } } } command_tree_node { tree { data: e790eaa8098caa3ef3a44d22518481a2e78320dd } index: 8 } }

but the buffer i get back is only 2 bytes per pixel.

**Comment by ben-clayton** [comment]
57957d073
