### ISSUE TITLE
Scrubber selection issues

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#18]
- When a a node is selected in the command tree, the scrubber needs to know which frame to highlight as the current selection
- When a frame in the scrubber is selected, resolving the path.Command from the service.Event will return a CTN that represents the last command in the frame, rather than the group representing that frame

**Comment by ben-clayton** [comment]
> * When a a node is selected in the command tree, the scrubber needs to know which frame to highlight as the current selection

Select the first frame with the command after the last atom in the group.

> * When a frame in the scrubber is selected, resolving the path.Command from the service.Event will return a CTN that represents the last command in the frame, rather than the group representing that frame

As discussed, can you select the actual node, but only jump to the deepest ancestor for that node?
