### ISSUE TITLE
Add some fields to service.CommandTreeNode

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#3]
I need the following for nodes that represent groups:
Path.Command to use for thumbnail (empty if none should be shown) - this can be an interim solution until we figure something out that works better with Vulkan
Path.Command to use for texture, shader, memory, etc views, when a group is selected
Index of first command and number of commands for display purposes.

**Comment by ben-clayton** [comment]
> Path.Command to use for thumbnail (empty if none should be shown) - this can be an interim solution until we figure something out that works better with Vulkan

Instead of adding a field to the `CommandTreeNode`, I've added `CommandTreeNode` support to `path.Thumbnail` - see 9b59ad7.

**Comment by ben-clayton** [comment]
> Path.Command to use for texture, shader, memory, etc views, when a group is selected
Index of first command and number of commands for display purposes.

Restructured the `CommandTreeNode` to always have a command field in dcf6ab4. I think we need to discuss the "number of commands" bit. Remind me to bring it up in today's meeting, perhaps?

**Comment by pmuetschard** [comment]
re: 9b59ad7 - So we are now assuming there will always be a relevant thumbnail for a group? We may want to add an error type that says that the thumbnail should be ignored.

re: dcf6ab4 - This helps with selection, great. I still need the path to the first command in order to show the index for the group.

re: counts - I think they are useful, it makes it easy to find a frame that all of a sudden does a lot of extra stuff, for example. I understand that, especially for Vulkan, not all commands are equal, but it's still an overall helpful perf measure. I envision the following hierarchy for Vulkan, which makes sense to me:

```
frame x (57 commands)
- 4400: vkWhatever
- 4401: vkSomethingElse
- ...
- 4455: vkQueueSubmit (23 subcomands)
  - 4455.0: vkCmdWhatever
  - 4455.1: vkCmdMoarStuff
  - ...
  - 4455.22: vkSoMuchFun
- 4456: vkWaitForFences
```

Even if subcommands have subcommands it makes sense to me.

**Comment by ben-clayton** [comment]
> So we are now assuming there will always be a relevant thumbnail for a group

I would have thought you'd get an `ErrDataUnavailable` in this case, but I could be wrong.

> This helps with selection, great. I still need the path to the first command in order to show the index for the group.

Humm, let me think about that a little.

> re: counts

The trouble is counting is expensive, and it can undo all the laziness we're trying to do. I think this is a Nice To Have, and maybe we should revisit it.
