### ISSUE TITLE
Command Tree filtering by context does not work

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#4]
GET command_tree { capture { id { data: 1abfba1bb57bc960f0b230587e126d34e9c52ae9 } } }
GET command_tree { capture { id { data: 1abfba1bb57bc960f0b230587e126d34e9c52ae9 } } context { data: d0e2d452f40db8783c4776f0d7ad6d6c20b7093c } }

Although they return two different root paths, the resulting trees still contain all commands.

**Comment by ben-clayton** [comment]
Yup. There's a big fat TODO in there.

**Comment by ben-clayton** [comment]
Done. See:

45cfa8668d219be8f2dfdd7fb7fabb5a4352af16
0d23a969ba9be715d570444d92f94beacaad6cf8
681b579e1f9bb88fbb289b61ef0bd95953aacda8
