### ISSUE TITLE
service.Parameter name is all lowercase

### ISSUE THREAD

**Issue by pmuetschard** [ben-clayton/gapid#6]
The parameter names are now all lowercase. While I don't care about the first letter in the name, the camel case should be maintained:
expected: [bB]ufferBytesWritten
actual: bufferbyteswritten

**Comment by ben-clayton** [comment]
Really we should be consistent with snake-case parameter names. Fixed anyway. cb0d8c6ea

**Comment by pmuetschard** [comment]
FWIW, GL and Vulkan both use camel case for their arguments in the documentation and headers, with the first letter being lowercase.
